name: todocheck-bot

on:
  issues:
    types: [closed]

jobs:
  todocheck-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Execute todocheck-bot
        uses: actions/todocheck-bot
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-numbers: github.event.issue.number